### ISSUE TITLE
Design styles to switch Catalog filter block to the right

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#409]
We'll add the feature to set up the Catalog filter position in the admin dashboard. It's needed to get to know what classes should be changed. It seems it could be done with the following changes:

```CSS

.grid-container {
  grid-auto-flow: dense;
}

.product-filter {
  grid-column: 4 / 5;
}

.product-list {
  grid-column: 1 / 4;
}
```
It will change the UI as follows:
![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/79427eb1-e530-4181-b263-9191866063ba)

We need to design the Tailwind classes changes to place the filter block to the right.

And we need to fix the issue of the absence of the gap between Filter block and Product list for both layouts. Most likely it can be resolved by adding column gaps to the grid container and inherit these gaps tho the sub-grid container (product list).
